version: '3'

services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    #ports:
    #  - 3000:1337
    environment:
      - BASE_URL=https://planka-prcf.onrender.com
      - DATABASE_URL=postgresql://planka_db_tu9p_user:IWZkYxUReqQjVf4M37tfRCPs9CZ8HSV9@dpg-cvrrvdjuibrs73bpgt00-a.frankfurt-postgres.render.com/planka_db_tu9p
      - NODE_ENV=development
      - PGSSLMODE=require
      - SECRET_KEY=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDe6S6EXlgmfSl2
TKctJEtCaDq/OzYDXjLNd+8/LTh20gH6aCcyqciODkhLo0BFpOTr+H8Us76ECl/1
YSj+ozRrrWtlvd6Tl0IrqG+pzzcELE+Q2ea7wOICflfI9jakqtq1hSGesr2lEa2i
l0HfGXndpRcuh12tRze0WKFTfjLBb01VIZt5JmCBtc/A/KExTv8nOv5FyiCmKXwM
2SPaMz/vpeermZfyVfW0e5jhKiwn5gCUyhTMw+FKGwqlQxVvOAwV8A/RVlnInEXD
xcOBE/dRMGcLvk7FnfFJFxmF8zw6iOpcee1urCxqWVd9ohHCSO5dlPUqx8W001Qf
r4SwnjyPAgMBAAECggEBAJFBfjB/kg2yrdwK4z2FUw15Ah8vJGlZbt15dAvFGfBD
tUpJqJFZFfmL0QyI2w8G/q3OBnGlF1bPs+wgXihgjX5FSaDI80tV26a7YdhT0VQE
0+xeMf7TF/PsBKRN3Rm8xDxY/ql9bBsuw+kZi7En1sPaGpsVVrPdnq0EvEu+BrEI
8OQ74pCjNDr90JLA1kjSc6IKR5mBVarpY3sFCHPmg7E7vHu3t0SKTJGvbRLV7ysg
YxLJTFbg8Vh/cWr2nfPE/THIzWhfc/o99WuvKCDyZYtxYQw82jQohpdhAUEhgYch
vvbo1hp3+iSmFMMZm07gLsM16oCwRm5x9Zz5HyXVG9ECgYEA91kWBL/ZEv1guhoX
4vLpZe6NZYrk7ZqSwMhTqGi9a5fnL5CCTINEYZn2Cd3ryZd8nv33QA7KTiruAvI2
eCn4NXZKT9RrdyySPn2/CPh7CfqKZp8y+DW6jgMtpRJN/AG1PLSppF8V6lpVCF5H
4GIxMqRL6xFh1PiLhVqmEkekOXMCgYEA5rVFFT11H/hA02vsZdns0bLJO7iZjdkb
5wNMZ+58ub2keiBRJb00BzKVZDj43G/440EsGyDN2YMikHFitqYXJ3LPDoVALCbM
tPvJicYfGr3YAS59dtqu0uD3qHJuGQa6upBN8o2Es9ufsHpGN4LEjl+LQZGF1hRo
rliRiGFNWXUCgYEAlTknsYHUgkJewqfPVVnbOWWr5GDhL/+bHbc90VIvROQF04pJ
McPX01JBPz6la596zajGK91Aa9w2b4yVE/WuCwLsXjD3DJTVPeI7CDxwblq6eKL+
6wPvIpIETZw3dBvLrW4JEmNTI2mP91Z54oMaz0STkKOR9Bxmf/NqUYjrKMUCgYEA
xwIOeWfuJImswbMS1DjLw4eJdm6iZm2lV/zMZ8qc5EvmGULPPNKckqjbnPxYDy63
brDFLxF4/+vSYO6tzAgxaOHsIgZneK5vXp7jFmlEY3jnXv2PVHsG2vkcKL2sowHf
CRd5ZYUVt1/3u+99qlyu2HEqWoEBBc3NDrdvskjcxBECgYAn5UqCTW8mIQ9D8i1m
D1MjqTy+lK2FklVbghbyFyOTtO6Nqu71LquO0GNwN21iLgkyQgMObjRkwocCc4SK
KuAfA4+j0mul41dBJtxvFUqB98Ksev71NDJfgai1497M4VT3mM9JYwSO8Iy163mj
Uu5gAhE8p+l04QfIax0QN1ed8Q==

      # - TRUST_PROXY=0
      # - TOKEN_EXPIRES_IN=365 # In days

      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      # - DEFAULT_ADMIN_EMAIL=demo@demo.demo # Do not remove if you want to prevent this user from being edited/deleted
      # - DEFAULT_ADMIN_PASSWORD=demo
      # - DEFAULT_ADMIN_NAME=Demo Demo
      # - DEFAULT_ADMIN_USERNAME=demo

      # - SHOW_DETAILED_AUTH_ERRORS=false # Set to true to show more detailed authentication error messages. It should not be enabled without a rate limiter for security reasons.
      # - ALLOW_ALL_TO_CREATE_PROJECTS=true

      # - S3_ENDPOINT=
      # - S3_REGION=
      # - S3_ACCESS_KEY_ID=
      # - S3_SECRET_ACCESS_KEY=
      # - S3_BUCKET=
      # - S3_FORCE_PATH_STYLE=true

      # - OIDC_ISSUER=
      # - OIDC_CLIENT_ID=
      # - OIDC_CLIENT_SECRET=
      # - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=
      # - OIDC_USERINFO_SIGNED_RESPONSE_ALG=
      # - OIDC_SCOPES=openid email profile
      # - OIDC_RESPONSE_MODE=fragment
      # - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_CLAIMS_SOURCE=userinfo
      # - OIDC_EMAIL_ATTRIBUTE=email
      # - OIDC_NAME_ATTRIBUTE=name
      # - OIDC_USERNAME_ATTRIBUTE=preferred_username
      # - OIDC_ROLES_ATTRIBUTE=groups
      # - OIDC_IGNORE_USERNAME=true
      # - OIDC_IGNORE_ROLES=true
      # - OIDC_ENFORCED=true

      # Email Notifications (https://nodemailer.com/smtp/)
      # - SMTP_HOST=
      # - SMTP_PORT=587
      # - SMTP_NAME=
      # - SMTP_SECURE=true
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_FROM="Demo Demo" <demo@demo.demo>
      # - SMTP_TLS_REJECT_UNAUTHORIZED=false

      # Optional fields: accessToken, events, excludedEvents
      # - |
      #   WEBHOOKS=[{
      #     "url": "http://localhost:3001",
      #     "accessToken": "notaccesstoken",
      #     "events": ["cardCreate", "cardUpdate", "cardDelete"],
      #     "excludedEvents": ["notificationCreate", "notificationUpdate"]
      #   }]

      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=

      # - GOOGLE_CHAT_WEBHOOK_URL=

      # - TELEGRAM_BOT_TOKEN=
      # - TELEGRAM_CHAT_ID=
      # - TELEGRAM_THREAD_ID=
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
